syntax = "proto3";

package prediction;

service PredictionService {
    rpc ObserveProgress(PredictionProgressRequest) returns (stream PredictionProgressResponse);
}

message PredictionProgressRequest {
    string jobId = 1;
}

message PredictionProgressResponse {
    /**
     * Progress of prediciton. That's the natural number between 0 (start) and 100 (finish).
     */
    int32 progress = 1;
    /**
     * List of result, present when prediction is finished.
     */
    repeated int32 result = 2;
}